apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.gardener.cloud
spec:
  resources:
  - group: core.gardener.cloud
    name: secretbindings
    schema: v251128-fdd9f37cc.secretbindings.core.gardener.cloud
    storage:
      crd: {}
  - group: core.gardener.cloud
    name: shoots
    schema: v251128-fdd9f37cc.shoots.core.gardener.cloud
    storage:
      crd: {}
  permissionClaims:
  - group: "" 
    resource: secrets
    verbs: ["*"]
status: {}
