kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: kcp
  namespace: garden-kcp
spec:
  provider:
    type: aws
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.180.0.0/16
        zones:
          - name: eu-west-1b
            workers: 10.180.0.0/19
            public: 10.180.32.0/20
            internal: 10.180.48.0/20
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
      - name: worker-eplnj
        minimum: 1
        maximum: 2
        maxSurge: 1
        machine:
          type: m5.large
          image:
            name: gardenlinux
            version: 1877.6.0
          architecture: amd64
        zones:
          - eu-west-1b
        cri:
          name: containerd
        volume:
          type: gp3
          size: 50Gi
  networking:
    nodes: 10.180.0.0/16
    type: calico
  kubernetes:
    version: 1.33.5
  cloudProfile:
    name: aws
    kind: CloudProfile
  secretBindingName: mcpkcp-aws
  purpose: evaluation
  region: eu-west-1
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
    timeWindow:
      begin: 020000+0200
      end: 030000+0200
  hibernation:
    schedules:
      - location: Europe/Vilnius
        start: 00 17 * * 1,2,3,4,5
